services:
  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - 13306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - 8080:80
    restart: always
    env_file:
      - .env

volumes:
  db_data:
